name: freelance
version: 1.13.8+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  growerp_sales: ^1.9.0
  growerp_website: ^1.9.0
  growerp_inventory: ^1.9.0
  growerp_catalog: ^1.9.0
  growerp_order_accounting: ^1.9.0
  growerp_user_company: ^1.9.0
  growerp_activity: ^1.8.1
  growerp_marketing: ^1.9.0
  growerp_outreach:
    path: ../growerp_outreach
  universal_io: ^2.2.2
  global_configuration: ^2.0.0
  responsive_framework: ^1.4.0
  flutter_simple_treeview: ^3.0.2
  printing: ^5.14.0
  pdf: ^3.10.8
  bloc_concurrency: ^0.2.0
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  hive_flutter: ^1.1.0
  fl_chart: ^1.1.0
  go_router: ^14.6.2
  dio: ^5.4.3
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.2
  flutter_lints: ^6.0.0

  bloc_test: ^9.0.1
  # flutter_launcher_icons: ^0.9.2
# to run icons: flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "packages/growerp_core/images/freelanceStore.jpg"

flutter:
  uses-material-design: true
  generate: true

  # from https://www.flaticon.com/
  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
flutter_intl:
  enabled: true
