name: growerp
resolution: workspace
version: 1.11.6
description: GrowERP installation and tools such as import and export.
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp/tree/master/flutter/packages/growerp
platforms:
  linux:
  macos:
  windows:
executables:
  growerp: growerp
  convertToCsv: convert_to_csv
environment:
  sdk: ^3.9.0
dependencies:
  archive: ^3.6.1
  dcli: ^8.4.2
  dio: ^5.4.3
  fast_csv: ^0.2.6
  get_it: ^9.2.1
  growerp_models: ^1.11.6
  hive: ^2.2.3
  logger: ^2.0.2+1
  path: ^1.8.3
  retrofit: ^4.9.2
  pretty_dio_logger: ^1.3.1
  spreadsheet_decoder: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
