name: health
version: 1.12.7+1
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
publish_to: none
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0
dependencies:
  flutter:
    sdk: flutter
  growerp_sales: ^1.9.0
  growerp_website: ^1.9.0
  growerp_order_accounting: ^1.9.0
  growerp_user_company: ^1.9.0
  growerp_activity: ^1.8.1
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  decimal: ^3.2.4
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  hive_flutter: ^1.1.0
  web: ^1.0.0
  dio: ^5.4.3
  http: ^1.1.2
  go_router: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  webdriver: ^3.0.2
  test: ^1.19.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
flutter_intl:
  enabled: true
