name: growerp_website
description: A website component for the GrowERP system.
version: 1.10.5
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  growerp_core: ^1.9.0
  growerp_models: ^1.9.0
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  responsive_framework: ^1.4.0
  archive: ^4.0.7
  path_provider: ^2.0.11
  reorderables: ^0.6.0
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.1.0
  from_css_color: ^2.0.0
  bloc_concurrency: ^0.2.0
  image_picker: ^1.0.4
  global_configuration: ^2.0.0
  file_picker: ^10.1.2
  stream_transform: ^2.1.0
  decimal: ^3.2.4
  #  html_editor_enhanced: ^2.5.1
  markdown_widget: ^2.3.1
  dropdown_search: ^5.0.6
  dio: ^5.4.3
  universal_io: ^2.2.2
  flutter_test:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.16.0
flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
