name: growerp_sales_example
resolution: workspace
version: 0.0.0+0
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  growerp_sales: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
    
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
flutter_intl:
  enabled: true
