name: growerp_core
description: The Core of the GrowERP frontend
version: 1.10.5
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0
dependencies:
  growerp_models: ^1.11.6
  growerp_chat: ^1.9.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  decimal: ^3.2.4
  intl: ^0.20.2
  global_configuration: ^2.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.0
  meta: ^1.3.0
  image_picker: ^1.0.4
  responsive_framework: ^1.4.0
  flutter_simple_treeview: ^3.0.2
  dropdown_search: ^5.0.6
  printing: ^5.14.0
  pdf: ^3.10.8
  about: ^2.1.1
  web_socket_channel: ^3.0.2
  shared_preferences: ^2.3.2
  stream_transform: ^2.1.0
  collection: ^1.16.0
  dio: ^5.4.3
  credit_card_validator: ^2.0.1
  markdown_widget: ^2.3.1
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.1.0
  from_css_color: ^2.0.0
  path_provider: ^2.0.11
  file_picker: ^10.3.10
  fast_csv: ^0.2.6
  archive: ^4.0.7
  image: ^4.0.17
  flutter_staggered_grid_view: ^0.7.0
  retrofit: 4.9.0
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1
  http: ^1.1.2
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.5.0
  flutter_flow_chart: ^2.2.0
  star_menu: ^4.0.1
  two_dimensional_scrollables: ^0.3.1
  universal_io: ^2.2.2
  flex_color_scheme: ^8.3.0
  go_router: ^14.6.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  growerp_activity: ^1.8.1
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  google_fonts: ^6.3.3
  animations: ^2.1.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  json_serializable: ^6.10.0
  retrofit_generator: 10.0.6
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
