name: growerp_marketing_example
resolution: workspace
description: A example project showcasing growerp_marketing package features.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_marketing: ^1.9.0
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  global_configuration: ^2.0.0
  flutter_bloc: ^8.1.0
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
