name: marketing_example
description: A example project showcasing growerp_marketing package features.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_marketing:
    path: ../
  growerp_core:
    path: ../../growerp_core
  growerp_models:
    path: ../../growerp_models
  global_configuration: ^2.0.0
  flutter_bloc: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - packages/growerp_core/images/assessment-color.png
    - packages/growerp_core/images/assessment-grey.png
