name: admin
resolution: workspace
version: 1.13.9+99
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
publish_to: none
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0
dependencies:
  flutter:
    sdk: flutter
  growerp_sales: ^1.9.0
  growerp_marketing: ^1.9.0
  growerp_website: ^1.9.0
  growerp_inventory: ^1.9.0
  growerp_catalog: ^1.9.0
  growerp_order_accounting: ^1.9.0
  growerp_user_company: ^1.9.0
  growerp_activity: ^1.8.1
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  decimal: ^3.2.4
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  hive_flutter: ^1.1.0
  universal_io: ^2.2.2
  cupertino_icons: ^1.0.8
  web: ^1.0.0
  flutter_bloc: ^8.1.4
  dio: ^5.4.3
  http: ^1.1.2
  fl_chart: ^1.1.0
  get_it: ^8.0.3
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  file_picker: ^10.3.10
  go_router: ^14.6.2
  growerp_outreach: ^0.0.1
  growerp_courses: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  webdriver: ^3.0.2
  test: ^1.19.5
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.12

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

msix_config:
  display_name: GrowERP
  publisher: CN=68EEF479-7015-49FC-9C60-33E5A2EB731C
  publisher_display_name: "AntWebsystems Co.,Ltd"
  identity_name: AntWebsystemsCo.LTD.GrowERP
  msix_version: 1.13.9.0
  logo_path: "assets/icon/icon.png"
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
flutter_intl:
  enabled: true
