name: growerp_core
description: The Core of the GrowERP frontend
version: 0.9.3
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp/tree/master/packages/growerp_core
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  decimal: ^2.1.0
  reorderables: ^0.6.0
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  meta: ^1.3.0
  image_picker: ^0.8.5
  responsive_framework: ^1.0.0
  flutter_simple_treeview: ^3.0.2
  dropdown_search: ^4.0.1
  printing: ^5.10.4
  pdf: ^3.10.0
  about: ^2.1.1
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.15
  date_utils: ^0.2.0
  cupertino_icons: ^1.0.5
  stream_transform: ^2.1.0
  collection: ^1.16.0
  http: ^0.13.5
  flutter_lints: ^2.0.1
  json_annotation: ^4.7.0
  dio: ^5.0.1
  freezed_annotation: ^2.0.3
  credit_card_validator: ^2.0.1
  markdown_widget: ^2.1.0
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.0.3
  from_css_color: ^2.0.0
  path_provider: ^2.0.11
  file_picker: ^5.0.1
  fast_csv: ^0.1.44
  archive: ^3.3.0
  image: ^4.0.2
  flutter_test: 
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  material_color_utilities: ^0.2.0
dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  flutter_driver: 
    sdk: flutter
  freezed: ^2.0.3
  mockito: ^5.0.2
  bloc_test: ^9.0.1
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.4
  json_serializable: ^6.2.0
  dependency_validator: ^3.2.0
flutter: 
  uses-material-design: true
flutter_intl: 
  enabled: true
