name: growerp_catalog
description: >
  A catalog component for the Growerp ERP System containing, products, categories and assets
version: 1.10.5
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  growerp_core: ^1.9.0
  growerp_models: ^1.9.0
  intl: ^0.20.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  responsive_framework: ^1.4.0
  archive: ^4.0.7
  path_provider: ^2.0.11
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.1.0
  from_css_color: ^2.0.0
  bloc_concurrency: ^0.2.0
  image_picker: ^1.0.4
  global_configuration: ^2.0.0
  file_picker: ^10.1.2
  stream_transform: ^2.1.0
  decimal: ^3.2.4
  fast_csv: ^0.2.6
  dropdown_search: ^5.0.6
  universal_io: ^2.2.2
  two_dimensional_scrollables: ^0.3.1
  dio: ^5.4.3
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  fl_chart: ^1.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.16.0
flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerpDark100.png
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
