name: hotel
version: 1.12.0+29
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_core: ^1.9.0
  growerp_sales: ^1.9.0
  growerp_website: ^1.9.0
  growerp_inventory: ^1.9.0
  growerp_catalog: ^1.9.0
  growerp_order_accounting: ^1.9.0
  growerp_user_company: ^1.9.0
  growerp_activity: ^1.8.1
  package_info_plus: ^8.0.2
  horizontal_data_table: ^4.3.1
  flutter_localizations:
    sdk: flutter
  universal_io: ^2.2.2
  intl: ^0.20.2
  fl_chart: ^1.1.0
  go_router: ^14.6.2
  dio: ^5.4.3
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^5.0.3
  bloc_test: ^9.0.1
  flutter_lints: ^6.0.0
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: packages/growerp_core/images/hotel1.jpg

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png

flutter_intl:
  enabled: true
