name: growerp_order_accounting
description: >
  A package providing order and accounting functions such as order, invoice,       
   \n \n \n payments and ledger for the GrowERP system both for sales and   
  \n\npurchase.\n\n\n\n\n\n\n
version: 0.9.2
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp/tree/master/packages/growerp_order_accounting
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  decimal: ^2.1.0
  reorderables: ^0.6.0
  intl: ^0.17.0
  global_configuration: ^2.0.0-nullsafety.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0
  meta: ^1.3.0
  image_picker: ^0.8.5
  responsive_framework: ^1.0.0
  flutter_simple_treeview: ^3.0.2
  dropdown_search: ^4.0.1
  printing: ^5.10.4
  pdf: ^3.10.3
  image: ^4.0.17
  about: ^2.1.1
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.15
  date_utils: ^0.2.0
  cupertino_icons: ^1.0.5
  stream_transform: ^2.1.0
  collection: ^1.16.0
  json_annotation: ^4.7.0
  dio: ^5.0.2
  freezed_annotation: ^2.0.3
  freezed: ^2.0.3
  credit_card_validator: ^2.0.1
  markdown_widget: ^2.1.0
  url_launcher: ^6.1.4
  flutter_colorpicker: ^1.0.3
  from_css_color: ^2.0.0
  path_provider: ^2.0.11
  file_picker: ^5.0.1
  fast_csv: ^0.1.44
  archive: ^3.3.0
  flutter_test: 
    sdk: flutter
  growerp_core: ^0.9.2
  scrollable_positioned_list: ^0.3.8
dependency_overrides: 
  intl: ^0.18.0
dev_dependencies: 
  flutter_driver: 
    sdk: flutter
  integration_test: 
    sdk: flutter
  mockito: ^5.0.2
  very_good_analysis: ^3.0.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.4
  json_serializable: ^6.2.0
  dependency_validator: ^3.2.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/growerp_core/images/report.png
    - packages/growerp_core/images/reportGrey.png
    - packages/growerp_core/images/setup.png
    - packages/growerp_core/images/setupGrey.png
    - packages/growerp_core/images/about.png
    - packages/growerp_core/images/aboutGrey.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/categoryGrey.png
    - packages/growerp_core/images/addImage.png
    - packages/growerp_core/images/categories.png
    - packages/growerp_core/images/company.png
    - packages/growerp_core/images/favicon-32x32.png
    - packages/growerp_core/images/growerpPlaystore.png
    - packages/growerp_core/images/orderGrey.png
    - packages/growerp_core/images/supplierGrey.png
    - packages/growerp_core/images/crmGrey.png
    - packages/growerp_core/images/growerp1024x500.jpg
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/order.png
    - packages/growerp_core/images/supplier.png
    - packages/growerp_core/images/accountingGrey.png
    - packages/growerp_core/images/category.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp50x50.jpg
    - packages/growerp_core/images/infoGrey.png
    - packages/growerp_core/images/personInfo.png
    - packages/growerp_core/images/up-arrow.png
    - packages/growerp_core/images/accounting.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/dashBoardGrey.png
    - packages/growerp_core/images/growerp512x512.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/productsGrey.png
    - packages/growerp_core/images/usersGrey.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/dashBoard.png
    - packages/growerp_core/images/growerpAppstore.png
    - packages/growerp_core/images/myInfoGrey.png
    - packages/growerp_core/images/products.png
    - packages/growerp_core/images/users.png
    - packages/growerp_core/images/categoriesGrey.png
    - packages/growerp_core/images/companyGrey.png
    - packages/growerp_core/images/export.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/myInfo.png
    - packages/growerp_core/images/search.png
    - packages/growerp_core/images/chat.png
    - packages/growerp_core/images/chatGrey.png
    - packages/growerp_core/images/info.png
    - packages/growerp_core/images/infoGrey.png
