name: growerp_models
version: 1.10.5
description: GrowERP models and Moqui backend REST interface
homepage: https://www.growerp.com
repository: https://github.com/growerp/growerp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  decimal: ^3.2.4
  equatable: ^2.0.5
  freezed_annotation: ^3.1.0
  dio: ^5.4.3
  retrofit: 4.9.0
  pretty_dio_logger: ^1.3.1
  fast_csv: ^0.2.6
  logger: ^2.0.2+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^4.0.0
  path_provider: ^2.1.1
  universal_io: ^2.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  freezed: ^3.2.0
  retrofit_generator: 10.0.6
