name: support
resolution: workspace
description: System support app, for the GrowERP system
version: 1.13.12+11
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
publish_to: none
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_user_company: ^1.9.0
  growerp_activity: ^1.8.1
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  universal_io: ^2.2.2
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.4
  dio: ^5.4.3
  http: ^1.1.2
  bloc_concurrency: ^0.2.5
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  go_router: ^14.6.2
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  webdriver: ^3.0.2
  test: ^1.19.5
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - assets/icon/
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
flutter_intl:
  enabled: true
