name: admin
version: 0.6.0+63
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  core:
    path: ../core/
  growerp_marketing:
    path: ../growerp_marketing/
  decimal: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
        sdk: flutter
  flutter_phoenix: ^1.0.0
  global_configuration: ^2.0.0-nullsafety.0
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  package_info_plus: ^1.4.2

dev_dependencies:
  dependency_validator: ^3.2.0
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.19.5
  utils:
    path: ../utils/

flutter:
  uses-material-design: true
  # from https://www.flaticon.com/
  assets:
    - assets/images/
    - assets/cfg/
    - ./
    - packages/core/images/info.png
    - packages/core/images/infoGrey.png
    - packages/core/images/chat.png
    - packages/core/images/chatGrey.png
flutter_intl:
  enabled: true
