name: growerp_activity_example
resolution: workspace
version: 0.0.1+1
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_activity: ^1.8.1
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  growerp_order_accounting: ^1.9.0
  growerp_user_company: ^1.9.0
  decimal: ^3.2.4
  flutter_bloc: ^8.1.4
  go_router: ^14.6.2
  flutter_localizations:
    sdk: flutter
  global_configuration: ^2.0.0
  intl: ^0.20.2
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  hive_flutter: ^1.1.0
  flutter_flow_chart: ^2.2.0
  star_menu: ^4.0.1
  path_provider: ^2.0.11
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  webdriver: ^3.0.2
  test: ^1.19.5
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/cfg/
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerpDark100.png
flutter_intl:
  enabled: true
