name: growerp_chat
resolution: workspace
description: "Internal chat within the growerp system."
version: 1.10.5
repository: https://github.com/growerp/growerp
homepage: https://www.growerp.com
environment:
  sdk: ^3.9.0
  flutter: ^3.33.0

dependencies:
  flutter:
    sdk: flutter
  growerp_core: ^1.9.0
  growerp_models: ^1.11.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  responsive_framework: ^1.4.0
  global_configuration: ^2.0.0
  dropdown_search: ^5.0.6
  flutter_flow_chart: ^2.2.0
  decimal: ^3.2.4
  star_menu: ^4.0.1
  flutter_test:
    sdk: flutter
  dio: ^5.8.0+1
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.19.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - packages/growerp_core/images/growerp.png
    - packages/growerp_core/images/crm.png
    - packages/growerp_core/images/growerpDark100.png
    - packages/growerp_core/images/growerp100.png
    - packages/growerp_core/images/growerp.jpg
    - packages/growerp_core/images/growerpDark.jpg
